services:
  ducks-database:
    image: postgres:alpine
    container_name: coffee-databases
    ports:
      - "6003:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guitars