spring:
  datasource:
    url: jdbc:postgresql://localhost:6003/guitars
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization:  true
  sql:
    init:
      mode: always